In [23]:
import glob
import zipfile
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers,models
from sklearn.metrics import classification_report, confusion_matrix

# unzip images

In [1]:
# run only once to extract the images from folder CV_2023_SC_Dataset

# def unzip_data():
#     with zipfile.ZipFile("CV_2023_SC_Dataset.zip","r") as zip_ref:
#     zip_ref.extractall("data")
    
# unzip_data()

# Read images

In [3]:
x_train=[]
x_test=[]
folders_name=["personA","personB","personC","personD","personE"]
for name in folders_name:
    for img in glob.glob("data/{}/Train/*.png".format(name)):
        n=cv2.imread(img)
        n= cv2.resize(n, (300,300))
        x_train.append(n)
    for img in glob.glob("data/{}/Test/*.png".format(name)):
        n=cv2.imread(img)
        n= cv2.resize(n, (300,300))
        x_test.append(n)


In [4]:
x_train[30].shape
#len(cv_img)

(300, 300, 3)

# create labels

In [5]:
y_train=np.arange(200)
y_test=np.arange(40)

In [6]:
def create_labels(step_size,start,end):
    temp=np.arange(end)
    for idx, i in enumerate(range(start, end, step_size)):
        temp[i:i+step_size] = idx
    return temp

In [7]:
y_train=create_labels(40,0,200)
y_train
y_test=create_labels(8,0,40)
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4])

In [8]:
x_train

[array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  

In [9]:
x_train=np.array(x_train)
x_test=np.array(x_test)
x_train.shape

(200, 300, 300, 3)

In [10]:
x_test=x_test/255
x_train=x_train/255

In [11]:
x_train

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 

# Train Model

In [13]:
cnn=models.Sequential([
    layers.Conv2D(filters=32,kernel_size=(3,3),activation='relu',input_shape=(300,300,3)),
    layers.MaxPool2D((2,2)),
    
    layers.Conv2D(filters=64,kernel_size=(3,3),activation='relu'),
    layers.MaxPool2D((2,2)),
    
    layers.Flatten(),
    layers.Dense(64,activation='relu'),
    layers.Dense(5,activation='softmax')
])

cnn.compile(
optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy']
)

cnn.fit(x_train,y_train,epochs=5)

Epoch 1/5
7/7 [==============================] - 11s 1s/step - loss: 13.9475 - accuracy: 0.2400
Epoch 2/5
7/7 [==============================] - 11s 2s/step - loss: 0.9458 - accuracy: 0.6650
Epoch 3/5
7/7 [==============================] - 11s 1s/step - loss: 0.1975 - accuracy: 0.9250
Epoch 4/5
7/7 [==============================] - 10s 1s/step - loss: 0.0576 - accuracy: 0.9800
Epoch 5/5
7/7 [==============================] - 10s 1s/step - loss: 0.0045 - accuracy: 1.0000


In [14]:
cnn.evaluate(x_test,y_test)

2/2 [==============================] - 1s 113ms/step - loss: 0.2116 - accuracy: 0.9250


[0.21156291663646698, 0.925000011920929]

# Test Model

In [15]:
result=cnn.predict(x_test)

2/2 [==============================] - 1s 119ms/step


In [16]:
final_result=[]
for i in result:
    final_result.append(np.argmax(i))

In [17]:
folders_name[final_result[35]]

'personE'

In [18]:
folders_name[y_test[35]]

'personE'

In [24]:
final_result==y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True])

In [25]:
print(classification_report(y_test, final_result))


              precision    recall  f1-score   support

           0       0.89      1.00      0.94         8
           1       0.88      0.88      0.88         8
           2       0.88      0.88      0.88         8
           3       1.00      1.00      1.00         8
           4       1.00      0.88      0.93         8

    accuracy                           0.93        40
   macro avg       0.93      0.93      0.92        40
weighted avg       0.93      0.93      0.92        40



In [26]:
print(confusion_matrix(y_test, final_result))


[[8 0 0 0 0]
 [1 7 0 0 0]
 [0 1 7 0 0]
 [0 0 0 8 0]
 [0 0 1 0 7]]
